name: CI/CD App iLeader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install vite --save-dev

    # Step 5: Build the project
    - name: Build the project
      run: npm run build
