name: CI/CD App iLeader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout mã nguồn
    - name: Checkout repository
      uses: actions/checkout@v3

    # Bước 2: Thiết lập môi trường Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Bước 3: Cài đặt các dependencies
    - name: Install dependencies
      run: npm install

    # Bước 4: Build dự án
    - name: Build the project
      run: npm run build

    # (Tùy chọn) Bước 5: Deploy ứng dụng (Nếu cần)
    #- name: Deploy to Zalo Mini App
    #  run: npm run deploy

    # (Tùy chọn) Bước 6: Chạy test nếu có
    # - name: Run tests
    #   run: npm test
